# Site settings
title: AnabhraTyagi
description: "Anabhra Tyagi's website featuring her resume, hosted on GitHub"
url: "https://anabhratyagi.github.io"
author:
    name: Anabhra Tyagi
    email: anabhratyagi@gmail.com
    github_username: anabhratyagi
    url: "https://anabhratyagi.github.io"
    baseurl: ""
 
 keywords: "anabhratyagi, anabhra, tyagi, anabhra tyagi, cloud, computing, cloud computing, aws, amazon web services, salesforce, resume, msit, maharaja surajmal institute of technology, student"   
     
social-network-links:
  facebook: "https://www.facebook.com/anabhra.tyagi"
  linkedin:"https://www.linkedin.com/in/anabhra-tyagi/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
  - jekyll-seo-tag
  - jekyll-sitemap
  
 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
