# Site settings
title: anabhra tyagi
description: "Anabhra Tyagi's website featuring her resume, hosted on GitHub"
url: "https://anabhratyagi.github.io"
author: Anabhra Tyagi
    email: "anabhratyagi@gmail.com"
    url: "https://anabhratyagi.github.io"
    baseurl: ""
 ShowContactInfo: "True"
 
 keywords: "anabhratyagi, anabhra, tyagi, anabhra tyagi, cloud, computing, cloud computing, aws, amazon web services, salesforce, resume, msit, maharaja surajmal institute of technology, student"    
     
github_username: "anabhratyagi"

social-network-links:
  email: "anabhratyagi@gmail.com"
  facebook: "https://www.facebook.com/anabhra.tyagi"
  github: anabhratyagi
  linkedin:"https://www.linkedin.com/in/anabhra-tyagi/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - another-jekyll-plugin
  - jekyll-seo-tag
  - jekyll-sitemap
  
  gems:
        - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
